//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agencia()
        {
            this.Reserva_Vuelo = new HashSet<Reserva_Vuelo>();
        }
    
        public int AGE_CODIGO { get; set; }
        public string AGE_NOMBRE { get; set; }
        public string AGE_CORREO { get; set; }
        public string AGE_TELEFONO { get; set; }
        public string AGE_SITIO_WEB { get; set; }
        public string AGE_HORARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva_Vuelo> Reserva_Vuelo { get; set; }
    }
}
