//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        public int AVI_CODIGO { get; set; }
        public int AER_CODIGO { get; set; }
        public int ASI_CODIGO { get; set; }
        public string AVI_MODELO { get; set; }
        public string AVI_TIPO_RUTA { get; set; }
        public int AVI_CAPACIDAD { get; set; }
        public string AVI_EQUIPAJE { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        public virtual Asiento Asiento { get; set; }
    }
}
