//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ERR_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public System.DateTime ERR_FEC_HORA { get; set; }
        public string ERR_FUENTE { get; set; }
        public string ERR_NUMERO { get; set; }
        public string ERR_DESCRIPCION { get; set; }
        public string ERR_VISTA { get; set; }
        public string ERR_ACCION { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
