//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int EST_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public System.DateTime EST_FEC_HORA { get; set; }
        public string EST_NAVEGADOR { get; set; }
        public string EST_PLATAFORMA_DISPOSITIVO { get; set; }
        public string EST_FABRICANTE_DISPOSITIVO { get; set; }
        public string EST_VISTA { get; set; }
        public string EST_ACCION { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
