//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int EST_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public System.DateTime EST_FEC_HORA { get; set; }
        public string EST_NAVEGADOR { get; set; }
        public string EST_PLATAFORMA_DISPOSITIVO { get; set; }
        public string EST_FABRICANTE_DISPOSITIVO { get; set; }
        public string EST_VISTA { get; set; }
        public string EST_ACCION { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
