//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int EST_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public System.DateTime EST_FEC_HORA { get; set; }
        public string EST_NAVEGADOR { get; set; }
        public string EST_PLATAFORMA_DISPOSITIVO { get; set; }
        public string EST_FABRICANTE_DISPOSITIVO { get; set; }
        public string EST_VISTA { get; set; }
        public string EST_ACCION { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
