//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int RES_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public int HAB_CODIGO { get; set; }
        public System.DateTime RES_FECHA_INGRESO { get; set; }
        public System.DateTime RES_FECHA_SALIDA { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
