//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int RES_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public int HAB_CODIGO { get; set; }
        public System.DateTime RES_FECHA_INGRESO { get; set; }
        public System.DateTime RES_FECHA_SALIDA { get; set; }
    
        public virtual Habitacion Habitacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
