//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva_Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva_Vuelo()
        {
            this.Tiquete = new HashSet<Tiquete>();
        }
    
        public int RVU_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public int AGE_CODIGO { get; set; }
        public string RVU_MONEDA { get; set; }
        public decimal RVU_PRECIO_TOTAL { get; set; }
        public System.DateTime RVU_FECHA { get; set; }
    
        public virtual Agencia Agencia { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tiquete> Tiquete { get; set; }
    }
}
