//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        public int SES_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public System.DateTime SES_FEC_HORA_INICIO { get; set; }
        public System.DateTime SES_FEC_HORA_FIN { get; set; }
        public string SES_ESTADO { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
