//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public int VUE_CODIGO { get; set; }
        public Nullable<int> AER_CODIGO { get; set; }
        public int VUE_ORI_CODIGO { get; set; }
        public int VUE_DES_CODIGO { get; set; }
        public string VUE_TERMINAL { get; set; }
        public string VUE_PUERTA { get; set; }
        public System.DateTime VUE_HORA_PARTIDA { get; set; }
        public System.DateTime VUE_HORA_LLEGADA { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Aeropuerto Aeropuerto1 { get; set; }
    }
}
